/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author REX
 */
public class ADDWorkingdayHours extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ADDWorkingdayHours() {
        initComponents();
         table_update();
    }
    
     Connection con1;
        PreparedStatement insert;  
        
        private void table_update(){
            
          int c;
          
          try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            con1= DriverManager.getConnection("jdbc:mysql://localhost/cambridge","root","");
          
            insert = con1.prepareStatement("select * From workingdays_hours");
            
            ResultSet rs = insert.executeQuery();  
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)Table.getModel();
            Df.setRowCount(0);
            
            while(rs.next()) {
                
                Vector v2 = new Vector();
                
                for(int a=1; a<=c; a++) {
                    
                    v2.add(rs.getString("Identity_Card"));
                    v2.add(rs.getInt("no_working_days"));
                    v2.add(rs.getString("Monday"));
                    v2.add(rs.getString("Tuesday"));
                    v2.add(rs.getString("Wednesday"));
                    v2.add(rs.getString("Thursday"));
                    v2.add(rs.getString("Friday"));
                    v2.add(rs.getString("Saturday"));
                    v2.add(rs.getString("Sunday"));
                    v2.add(rs.getInt("Hours"));
                    v2.add(rs.getInt("minutes"));
                
                    
                }
                
                Df.addRow(v2);
                  
            }
         
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        day = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        txtMonday = new javax.swing.JCheckBox();
        txtWednesday = new javax.swing.JCheckBox();
        txtTuesday = new javax.swing.JCheckBox();
        txtThursday = new javax.swing.JCheckBox();
        txtFriday = new javax.swing.JCheckBox();
        txtSaturday = new javax.swing.JCheckBox();
        txtSunday = new javax.swing.JCheckBox();
        hr = new javax.swing.JSpinner();
        min = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jCheckBox6.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7" }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Identicard Number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("No of Working days");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Working days");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Working Time Per day");

        txtMonday.setText("Monday");
        txtMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMondayActionPerformed(evt);
            }
        });

        txtWednesday.setText("Wednesday");

        txtTuesday.setText("Tuesday");
        txtTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuesdayActionPerformed(evt);
            }
        });

        txtThursday.setText("Thursday");

        txtFriday.setText("Friday");

        txtSaturday.setText("Saturday");

        txtSunday.setText("Sunday");

        jLabel5.setText("Hours");

        jLabel6.setText("Minutes");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identicard Number", "No of working days", "Monday", "Tuesday", "Wenesday", "Thursday", "Fridayl", "Saturday", "Sunday", "Hours", "Minutes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("CAMBRIDGE UNIVERSITY");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Add Workind Days Hours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMonday)
                                    .addComponent(txtSaturday)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hr, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(txtSunday)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTuesday)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtWednesday)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtThursday)
                                        .addGap(40, 40, 40)
                                        .addComponent(txtFriday))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(day)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWednesday)
                            .addComponent(txtThursday)
                            .addComponent(txtFriday)
                            .addComponent(txtMonday)
                            .addComponent(jLabel3)
                            .addComponent(txtTuesday))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaturday)
                            .addComponent(txtSunday))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void txtMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMondayActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
          String id = Id.getText();
        String no_days = day.getSelectedItem().toString();
        Integer days = parseInt(no_days);
        Integer count = 0;
        String Monday = "";
        if(txtMonday.isSelected()){
            Monday = "√";
            count = count + 1;
        }
        String Tuesday = "";
        if(txtTuesday.isSelected()){
            Tuesday = "√";
            count = count + 1;
        }
        String Wednesday = "";
        if(txtWednesday.isSelected()){
            Wednesday = "√";
            count = count + 1;
        }
        String Thursday = "";
        if(txtThursday.isSelected()){
            Thursday = "√";
            count = count + 1;
        }
        String Friday = "";
        if(txtFriday.isSelected()){
            Friday = "√";
            count = count + 1;
        }
        String Saturday = "";
        if(txtSaturday.isSelected()){
            Saturday = "√";
            count = count + 1;
        }
        String Sunday = "";
        if(txtSunday.isSelected()){
            Sunday = "√";
            count = count + 1;
        }
        Integer hours = (Integer)hr.getValue();
        Integer minutes = (Integer)min.getValue();
       
        

   

            if(days == count){

                try {

                    Class.forName("com.mysql.jdbc.Driver");

                    con1= DriverManager.getConnection("jdbc:mysql://localhost/cambridge","root","");

                    insert = con1.prepareStatement("insert into workingdays_hours(Identity_Card ,no_working_days,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Hours,minutes)values(?,?,?,?,?,?,?,?,?,?,?)");

                    insert.setString(1, id);
                    insert.setInt(2, days);
                    insert.setString(3, Monday);
                    insert.setString(4, Tuesday);
                    insert.setString(5, Wednesday);
                    insert.setString(6, Thursday);
                    insert.setString(7, Friday);
                    insert.setString(8, Saturday);
                    insert.setString(9, Sunday);
                    insert.setInt(10, hours);
                    insert.setInt(11, minutes);
                    

                    insert.executeUpdate();

                    JOptionPane.showMessageDialog(this,"New Timetable format Added");
                    table_update();

                    // To clear the rcords in the form
                    Id.setText("");
                    day.setSelectedIndex(0);
                    txtMonday.setSelected(false);
                    txtTuesday.setSelected(false);
                    txtWednesday.setSelected(false);
                    txtThursday.setSelected(false);
                    txtFriday.setSelected(false);
                    txtSaturday.setSelected(false);
                    txtSunday.setSelected(false);
                    hr.setValue(0);
                    min.setValue(0);                    
                    Id.requestFocus();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            

        
                      
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuesdayActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
            TableModel model = Table.getModel();
        int j = Table.getSelectedRow();   // to get the data in form when the row is selected

        Id.setText(model.getValueAt(j, 0).toString());

        String no_days = model.getValueAt(j, 1).toString();
        switch(no_days){
            case "1":
            day.setSelectedIndex(1);
            break;
            case "2":
            day.setSelectedIndex(2);
            break;
            case "3":
            day.setSelectedIndex(3);
            break;
            case "4":
            day.setSelectedIndex(4);
            break;
            case "5":
            day.setSelectedIndex(5);
            break;
            case "6":
            day.setSelectedIndex(6);
            break;
            case "7":
            day.setSelectedIndex(7);
            break;
        }

        String Monday = model.getValueAt(j, 2).toString();
        if(Monday.equals("√")){
            txtMonday.setSelected(true);
        }
        else{
            txtMonday.setSelected(false);
        }

        String Tuesday = model.getValueAt(j, 3).toString();
        if(Tuesday.equals("√")){
            txtTuesday.setSelected(true);
        }
        else{
            txtTuesday.setSelected(false);
        }

        String Wednesday = model.getValueAt(j, 4).toString();
        if(Wednesday.equals("√")){
            txtWednesday.setSelected(true);
        }
        else{
            txtWednesday.setSelected(false);
        }

        String Thursday = model.getValueAt(j, 5).toString();
        if(Thursday.equals("√")){
            txtThursday.setSelected(true);
        }
        else{
            txtThursday.setSelected(false);
        }

        String Friday = model.getValueAt(j, 6).toString();
        if(Friday.equals("√")){
            txtFriday.setSelected(true);
        }
        else{
            txtFriday.setSelected(false);
        }

        String Saturday = model.getValueAt(j, 7).toString();
        if(Saturday.equals("√")){
            txtSaturday.setSelected(true);
        }
        else{
            txtSaturday.setSelected(false);
        }

        String Sunday = model.getValueAt(j, 8).toString();
        if(Sunday.equals("√")){
            txtSunday.setSelected(true);
        }
        else{
            txtSunday.setSelected(false);
        }

        hr.setValue(model.getValueAt(j, 9));
        min.setValue(model.getValueAt(j, 10));

        
        
                                       
        
        
    }//GEN-LAST:event_TableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
              TableModel model = Table.getModel();
        int j = Table.getSelectedRow();   // to get the data in form when the row is selected

        // validation to check whether the row is selected
        if(j == -1){
            JOptionPane.showMessageDialog(this,"Select the timetable format");
        }

        else{
            try {

                String id = Id.getText();
                String no_days = day.getSelectedItem().toString();
                Integer days = parseInt(no_days);
                Integer i = 0;
                String Monday = "";
                if(txtMonday.isSelected()){
                    Monday = "√";
                    i = i + 1;
                }
                String Tuesday = "";
                if(txtTuesday.isSelected()){
                    Tuesday = "√";
                    i = i + 1;
                }
                String Wednesday = "";
                if(txtWednesday.isSelected()){
                    Wednesday = "√";
                    i = i + 1;
                }
                String Thursday = "";
                if(txtThursday.isSelected()){
                    Thursday = "√";
                    i = i + 1;
                }
                String Friday = "";
                if(txtFriday.isSelected()){
                    Friday = "√";
                    i = i + 1;
                }
                String Saturday = "";
                if(txtSaturday.isSelected()){
                    Saturday = "√";
                    i = i + 1;
                }
                String Sunday = "";
                if(txtSunday.isSelected()){
                    Sunday = "√";
                    i = i + 1;
                }
                Integer hours = (Integer)hr.getValue();
                Integer minutes = (Integer)min.getValue();
                

                if(days == i){

                    int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to update this Employee ?","Warning",JOptionPane.YES_NO_OPTION);

                    if (dialogResult == JOptionPane.YES_OPTION) {

                        Class.forName("com.mysql.jdbc.Driver");

                        con1= DriverManager.getConnection("jdbc:mysql://localhost/cambridge","root","");

                        insert = con1.prepareStatement("update workingdays_hours set no_working_days=?, Monday=?, Tuesday=?, Wednesday=?, Thursday=?, Friday=?, Saturday=?, Sunday=?, Hours=?, minutes=? where 	Identity_Card=? ");

                        insert.setInt(1, days);
                        insert.setString(2, Monday);
                        insert.setString(3, Tuesday);
                        insert.setString(4, Wednesday);
                        insert.setString(5, Thursday);
                        insert.setString(6, Friday);
                        insert.setString(7, Saturday);
                        insert.setString(8, Sunday);
                        insert.setInt(9, hours);
                        insert.setInt(10, minutes);                     
                        insert.setString(11, id);

                        insert.executeUpdate();

                        JOptionPane.showMessageDialog(this,"Timetable format Updated");
                        table_update();

                        // To clear the rcords in the form
                        Id.setText("");
                        day.setSelectedIndex(0);
                        txtMonday.setSelected(false);
                        txtTuesday.setSelected(false);
                        txtWednesday.setSelected(false);
                        txtThursday.setSelected(false);
                        txtFriday.setSelected(false);
                        txtSaturday.setSelected(false);
                        txtSunday.setSelected(false);
                        hr.setValue(0);
                        min.setValue(0);
                       
                        Id.requestFocus();

                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"No of Working days are not equal the selected Working days");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
          TableModel model = Table.getModel();
        int j = Table.getSelectedRow();   // to get the data in form when the row is selected

        if(j == -1){
            JOptionPane.showMessageDialog(this,"Select the timetable format from the table you want to delete");
        }

        else{
            try {

                String id = Id.getText();

                int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to delete this record ?","Warning",JOptionPane.YES_NO_OPTION);

                if (dialogResult == JOptionPane.YES_OPTION) {

                    Class.forName("com.mysql.jdbc.Driver");

                    con1= DriverManager.getConnection("jdbc:mysql://localhost/cambridge","root","");

                    insert = con1.prepareStatement("delete from workingdays_hours where Identity_Card=? ");

                    insert.setString(1, id);

                    insert.executeUpdate();

                    JOptionPane.showMessageDialog(this,"record is Deleted");
                    table_update();

                    // To clear the rcords in the form
                    Id.setText("");
                    day.setSelectedIndex(0);
                    txtMonday.setSelected(false);
                    txtTuesday.setSelected(false);
                    txtWednesday.setSelected(false);
                    txtThursday.setSelected(false);
                    txtFriday.setSelected(false);
                    txtSaturday.setSelected(false);
                    txtSunday.setSelected(false);
                    hr.setValue(0);
                    min.setValue(0);                  
                    Id.requestFocus();

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ADDWorkingdayHours.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDWorkingdayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDWorkingdayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDWorkingdayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDWorkingdayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDWorkingdayHours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JSpinner hr;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner min;
    private javax.swing.JCheckBox txtFriday;
    private javax.swing.JCheckBox txtMonday;
    private javax.swing.JCheckBox txtSaturday;
    private javax.swing.JCheckBox txtSunday;
    private javax.swing.JCheckBox txtThursday;
    private javax.swing.JCheckBox txtTuesday;
    private javax.swing.JCheckBox txtWednesday;
    // End of variables declaration//GEN-END:variables
}
